# Generated by Django 4.0.1 on 2022-01-31 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.FloatField()),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('images', models.ImageField(upload_to='images/')),
                ('image1', models.ImageField(upload_to='images/')),
                ('image2', models.ImageField(upload_to='images/')),
                ('employee', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('house_type', models.CharField(choices=[('Massionette', 'Massionette')], max_length=2000)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('is_rent', models.BooleanField(default=False)),
                ('is_buy', models.BooleanField(default=False)),
                ('price', models.FloatField()),
                ('images', models.ImageField(upload_to='images/')),
                ('image1', models.ImageField(upload_to='images/')),
                ('image2', models.ImageField(upload_to='images/')),
                ('bedroom', models.IntegerField()),
                ('shower', models.IntegerField()),
                ('garage', models.IntegerField()),
                ('hse_features', models.TextField(blank=True, max_length=2500)),
                ('apt_features', models.TextField(blank=True, max_length=2500)),
                ('description', models.TextField(blank=True, max_length=2500)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=60, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=70)),
                ('user', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_type', models.CharField(blank=True, choices=[('Vehicle Parts & Accessories', 'Vehicle Parts & Accessories'), ('Car', 'Car'), ('Trucks & Trailers', 'Trucks & Trailers'), ('Buses & Microbuses', 'Buses & Microbuses'), ('Heavy Equipments', 'Heavy Equipments'), ('Watercrafts & Boats', 'Watercrafts & Boats')], max_length=2000, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('model', models.CharField(blank=True, max_length=200, null=True)),
                ('number_plate', models.CharField(blank=True, max_length=200, null=True)),
                ('year', models.IntegerField()),
                ('images', models.ImageField(upload_to='images/')),
                ('image1', models.ImageField(upload_to='images/')),
                ('image2', models.ImageField(upload_to='images/')),
                ('price', models.FloatField()),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
