# Generated by Django 4.0.1 on 2022-02-06 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0002_alter_house_house_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
