# Generated by Django 4.0.1 on 2022-02-07 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0003_car_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
