# Generated by Django 4.0.1 on 2022-02-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0004_alter_car_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='house_type',
            field=models.CharField(choices=[('Bungalow', 'Bungalow'), ('Massionete', 'Massionete'), ('Penthouse', 'Penthouse')], max_length=2000),
        ),
    ]
