# Generated by Django 4.0.1 on 2022-02-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0005_land_title_alter_house_house_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
