# Generated by Django 4.0.1 on 2022-02-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0006_alter_land_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_buy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='is_rent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='land',
            name='is_buy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='land',
            name='is_rent',
            field=models.BooleanField(default=False),
        ),
    ]
